version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: country-delight
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/country-delight?schema=public
      FIREBASE_API_KEY: AIzaSyCySBLnL4RRl43Dy-Q_279gDy3lXHFtDrw
      # - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"

volumes:
  pgdata:
